#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bds240792229_db")]
public partial class LinkDBDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void Insertdachuang(dachuang instance);
  partial void Updatedachuang(dachuang instance);
  partial void Deletedachuang(dachuang instance);
  #endregion
	
	public LinkDBDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["bds240792229_dbConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public LinkDBDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LinkDBDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LinkDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LinkDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<dachuang> dachuang
	{
		get
		{
			return this.GetTable<dachuang>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dachuang")]
public partial class dachuang : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _mainID;
	
	private string _name;
	
	private string _grade;
	
	private string _major;
	
	private string _sex;
	
	private System.Nullable<int> _q1;
	
	private System.Nullable<int> _q2;
	
	private System.Nullable<int> _q3;
	
	private System.Nullable<int> _q4;
	
	private System.Nullable<int> _q5;
	
	private System.Nullable<int> _q6;
	
	private System.Nullable<int> _q7;
	
	private System.Nullable<int> _q8;
	
	private System.Nullable<int> _q9;
	
	private System.Nullable<int> _q10;
	
	private System.Nullable<int> _q11;
	
	private System.Nullable<int> _q12;
	
	private System.Nullable<int> _q13;
	
	private System.Nullable<int> _q14;
	
	private System.Nullable<int> _q15;
	
	private System.Nullable<int> _q16;
	
	private System.Nullable<int> _q17;
	
	private System.Nullable<int> _q18;
	
	private System.Nullable<int> _q19;
	
	private System.Nullable<int> _q20;
	
	private System.Nullable<int> _q21;
	
	private System.Nullable<int> _q22;
	
	private string _q23;
	
	private System.Nullable<int> _q24;
	
	private System.Nullable<int> _q25;
	
	private System.Nullable<int> _q26;
	
	private System.Nullable<int> _q27;
	
	private System.Nullable<int> _q28;
	
	private System.Nullable<int> _q29;
	
	private System.Nullable<int> _q30;
	
	private System.Nullable<int> _q31;
	
	private System.Nullable<int> _q32;
	
	private System.Nullable<int> _q33;
	
	private System.Nullable<int> _q34;
	
	private System.Nullable<int> _q35;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmainIDChanging(int value);
    partial void OnmainIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OngradeChanging(string value);
    partial void OngradeChanged();
    partial void OnmajorChanging(string value);
    partial void OnmajorChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    partial void Onq1Changing(System.Nullable<int> value);
    partial void Onq1Changed();
    partial void Onq2Changing(System.Nullable<int> value);
    partial void Onq2Changed();
    partial void Onq3Changing(System.Nullable<int> value);
    partial void Onq3Changed();
    partial void Onq4Changing(System.Nullable<int> value);
    partial void Onq4Changed();
    partial void Onq5Changing(System.Nullable<int> value);
    partial void Onq5Changed();
    partial void Onq6Changing(System.Nullable<int> value);
    partial void Onq6Changed();
    partial void Onq7Changing(System.Nullable<int> value);
    partial void Onq7Changed();
    partial void Onq8Changing(System.Nullable<int> value);
    partial void Onq8Changed();
    partial void Onq9Changing(System.Nullable<int> value);
    partial void Onq9Changed();
    partial void Onq10Changing(System.Nullable<int> value);
    partial void Onq10Changed();
    partial void Onq11Changing(System.Nullable<int> value);
    partial void Onq11Changed();
    partial void Onq12Changing(System.Nullable<int> value);
    partial void Onq12Changed();
    partial void Onq13Changing(System.Nullable<int> value);
    partial void Onq13Changed();
    partial void Onq14Changing(System.Nullable<int> value);
    partial void Onq14Changed();
    partial void Onq15Changing(System.Nullable<int> value);
    partial void Onq15Changed();
    partial void Onq16Changing(System.Nullable<int> value);
    partial void Onq16Changed();
    partial void Onq17Changing(System.Nullable<int> value);
    partial void Onq17Changed();
    partial void Onq18Changing(System.Nullable<int> value);
    partial void Onq18Changed();
    partial void Onq19Changing(System.Nullable<int> value);
    partial void Onq19Changed();
    partial void Onq20Changing(System.Nullable<int> value);
    partial void Onq20Changed();
    partial void Onq21Changing(System.Nullable<int> value);
    partial void Onq21Changed();
    partial void Onq22Changing(System.Nullable<int> value);
    partial void Onq22Changed();
    partial void Onq23Changing(string value);
    partial void Onq23Changed();
    partial void Onq24Changing(System.Nullable<int> value);
    partial void Onq24Changed();
    partial void Onq25Changing(System.Nullable<int> value);
    partial void Onq25Changed();
    partial void Onq26Changing(System.Nullable<int> value);
    partial void Onq26Changed();
    partial void Onq27Changing(System.Nullable<int> value);
    partial void Onq27Changed();
    partial void Onq28Changing(System.Nullable<int> value);
    partial void Onq28Changed();
    partial void Onq29Changing(System.Nullable<int> value);
    partial void Onq29Changed();
    partial void Onq30Changing(System.Nullable<int> value);
    partial void Onq30Changed();
    partial void Onq31Changing(System.Nullable<int> value);
    partial void Onq31Changed();
    partial void Onq32Changing(System.Nullable<int> value);
    partial void Onq32Changed();
    partial void Onq33Changing(System.Nullable<int> value);
    partial void Onq33Changed();
    partial void Onq34Changing(System.Nullable<int> value);
    partial void Onq34Changed();
    partial void Onq35Changing(System.Nullable<int> value);
    partial void Onq35Changed();
    #endregion
	
	public dachuang()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mainID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int mainID
	{
		get
		{
			return this._mainID;
		}
		set
		{
			if ((this._mainID != value))
			{
				this.OnmainIDChanging(value);
				this.SendPropertyChanging();
				this._mainID = value;
				this.SendPropertyChanged("mainID");
				this.OnmainIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(10)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grade", DbType="NChar(10)")]
	public string grade
	{
		get
		{
			return this._grade;
		}
		set
		{
			if ((this._grade != value))
			{
				this.OngradeChanging(value);
				this.SendPropertyChanging();
				this._grade = value;
				this.SendPropertyChanged("grade");
				this.OngradeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_major", DbType="NChar(10)")]
	public string major
	{
		get
		{
			return this._major;
		}
		set
		{
			if ((this._major != value))
			{
				this.OnmajorChanging(value);
				this.SendPropertyChanging();
				this._major = value;
				this.SendPropertyChanged("major");
				this.OnmajorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="NChar(10)")]
	public string sex
	{
		get
		{
			return this._sex;
		}
		set
		{
			if ((this._sex != value))
			{
				this.OnsexChanging(value);
				this.SendPropertyChanging();
				this._sex = value;
				this.SendPropertyChanged("sex");
				this.OnsexChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q1", DbType="Int")]
	public System.Nullable<int> q1
	{
		get
		{
			return this._q1;
		}
		set
		{
			if ((this._q1 != value))
			{
				this.Onq1Changing(value);
				this.SendPropertyChanging();
				this._q1 = value;
				this.SendPropertyChanged("q1");
				this.Onq1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q2", DbType="Int")]
	public System.Nullable<int> q2
	{
		get
		{
			return this._q2;
		}
		set
		{
			if ((this._q2 != value))
			{
				this.Onq2Changing(value);
				this.SendPropertyChanging();
				this._q2 = value;
				this.SendPropertyChanged("q2");
				this.Onq2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q3", DbType="Int")]
	public System.Nullable<int> q3
	{
		get
		{
			return this._q3;
		}
		set
		{
			if ((this._q3 != value))
			{
				this.Onq3Changing(value);
				this.SendPropertyChanging();
				this._q3 = value;
				this.SendPropertyChanged("q3");
				this.Onq3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q4", DbType="Int")]
	public System.Nullable<int> q4
	{
		get
		{
			return this._q4;
		}
		set
		{
			if ((this._q4 != value))
			{
				this.Onq4Changing(value);
				this.SendPropertyChanging();
				this._q4 = value;
				this.SendPropertyChanged("q4");
				this.Onq4Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q5", DbType="Int")]
	public System.Nullable<int> q5
	{
		get
		{
			return this._q5;
		}
		set
		{
			if ((this._q5 != value))
			{
				this.Onq5Changing(value);
				this.SendPropertyChanging();
				this._q5 = value;
				this.SendPropertyChanged("q5");
				this.Onq5Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q6", DbType="Int")]
	public System.Nullable<int> q6
	{
		get
		{
			return this._q6;
		}
		set
		{
			if ((this._q6 != value))
			{
				this.Onq6Changing(value);
				this.SendPropertyChanging();
				this._q6 = value;
				this.SendPropertyChanged("q6");
				this.Onq6Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q7", DbType="Int")]
	public System.Nullable<int> q7
	{
		get
		{
			return this._q7;
		}
		set
		{
			if ((this._q7 != value))
			{
				this.Onq7Changing(value);
				this.SendPropertyChanging();
				this._q7 = value;
				this.SendPropertyChanged("q7");
				this.Onq7Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q8", DbType="Int")]
	public System.Nullable<int> q8
	{
		get
		{
			return this._q8;
		}
		set
		{
			if ((this._q8 != value))
			{
				this.Onq8Changing(value);
				this.SendPropertyChanging();
				this._q8 = value;
				this.SendPropertyChanged("q8");
				this.Onq8Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q9", DbType="Int")]
	public System.Nullable<int> q9
	{
		get
		{
			return this._q9;
		}
		set
		{
			if ((this._q9 != value))
			{
				this.Onq9Changing(value);
				this.SendPropertyChanging();
				this._q9 = value;
				this.SendPropertyChanged("q9");
				this.Onq9Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q10", DbType="Int")]
	public System.Nullable<int> q10
	{
		get
		{
			return this._q10;
		}
		set
		{
			if ((this._q10 != value))
			{
				this.Onq10Changing(value);
				this.SendPropertyChanging();
				this._q10 = value;
				this.SendPropertyChanged("q10");
				this.Onq10Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q11", DbType="Int")]
	public System.Nullable<int> q11
	{
		get
		{
			return this._q11;
		}
		set
		{
			if ((this._q11 != value))
			{
				this.Onq11Changing(value);
				this.SendPropertyChanging();
				this._q11 = value;
				this.SendPropertyChanged("q11");
				this.Onq11Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q12", DbType="Int")]
	public System.Nullable<int> q12
	{
		get
		{
			return this._q12;
		}
		set
		{
			if ((this._q12 != value))
			{
				this.Onq12Changing(value);
				this.SendPropertyChanging();
				this._q12 = value;
				this.SendPropertyChanged("q12");
				this.Onq12Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q13", DbType="Int")]
	public System.Nullable<int> q13
	{
		get
		{
			return this._q13;
		}
		set
		{
			if ((this._q13 != value))
			{
				this.Onq13Changing(value);
				this.SendPropertyChanging();
				this._q13 = value;
				this.SendPropertyChanged("q13");
				this.Onq13Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q14", DbType="Int")]
	public System.Nullable<int> q14
	{
		get
		{
			return this._q14;
		}
		set
		{
			if ((this._q14 != value))
			{
				this.Onq14Changing(value);
				this.SendPropertyChanging();
				this._q14 = value;
				this.SendPropertyChanged("q14");
				this.Onq14Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q15", DbType="Int")]
	public System.Nullable<int> q15
	{
		get
		{
			return this._q15;
		}
		set
		{
			if ((this._q15 != value))
			{
				this.Onq15Changing(value);
				this.SendPropertyChanging();
				this._q15 = value;
				this.SendPropertyChanged("q15");
				this.Onq15Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q16", DbType="Int")]
	public System.Nullable<int> q16
	{
		get
		{
			return this._q16;
		}
		set
		{
			if ((this._q16 != value))
			{
				this.Onq16Changing(value);
				this.SendPropertyChanging();
				this._q16 = value;
				this.SendPropertyChanged("q16");
				this.Onq16Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q17", DbType="Int")]
	public System.Nullable<int> q17
	{
		get
		{
			return this._q17;
		}
		set
		{
			if ((this._q17 != value))
			{
				this.Onq17Changing(value);
				this.SendPropertyChanging();
				this._q17 = value;
				this.SendPropertyChanged("q17");
				this.Onq17Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q18", DbType="Int")]
	public System.Nullable<int> q18
	{
		get
		{
			return this._q18;
		}
		set
		{
			if ((this._q18 != value))
			{
				this.Onq18Changing(value);
				this.SendPropertyChanging();
				this._q18 = value;
				this.SendPropertyChanged("q18");
				this.Onq18Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q19", DbType="Int")]
	public System.Nullable<int> q19
	{
		get
		{
			return this._q19;
		}
		set
		{
			if ((this._q19 != value))
			{
				this.Onq19Changing(value);
				this.SendPropertyChanging();
				this._q19 = value;
				this.SendPropertyChanged("q19");
				this.Onq19Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q20", DbType="Int")]
	public System.Nullable<int> q20
	{
		get
		{
			return this._q20;
		}
		set
		{
			if ((this._q20 != value))
			{
				this.Onq20Changing(value);
				this.SendPropertyChanging();
				this._q20 = value;
				this.SendPropertyChanged("q20");
				this.Onq20Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q21", DbType="Int")]
	public System.Nullable<int> q21
	{
		get
		{
			return this._q21;
		}
		set
		{
			if ((this._q21 != value))
			{
				this.Onq21Changing(value);
				this.SendPropertyChanging();
				this._q21 = value;
				this.SendPropertyChanged("q21");
				this.Onq21Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q22", DbType="Int")]
	public System.Nullable<int> q22
	{
		get
		{
			return this._q22;
		}
		set
		{
			if ((this._q22 != value))
			{
				this.Onq22Changing(value);
				this.SendPropertyChanging();
				this._q22 = value;
				this.SendPropertyChanged("q22");
				this.Onq22Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q23", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string q23
	{
		get
		{
			return this._q23;
		}
		set
		{
			if ((this._q23 != value))
			{
				this.Onq23Changing(value);
				this.SendPropertyChanging();
				this._q23 = value;
				this.SendPropertyChanged("q23");
				this.Onq23Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q24", DbType="Int")]
	public System.Nullable<int> q24
	{
		get
		{
			return this._q24;
		}
		set
		{
			if ((this._q24 != value))
			{
				this.Onq24Changing(value);
				this.SendPropertyChanging();
				this._q24 = value;
				this.SendPropertyChanged("q24");
				this.Onq24Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q25", DbType="Int")]
	public System.Nullable<int> q25
	{
		get
		{
			return this._q25;
		}
		set
		{
			if ((this._q25 != value))
			{
				this.Onq25Changing(value);
				this.SendPropertyChanging();
				this._q25 = value;
				this.SendPropertyChanged("q25");
				this.Onq25Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q26", DbType="Int")]
	public System.Nullable<int> q26
	{
		get
		{
			return this._q26;
		}
		set
		{
			if ((this._q26 != value))
			{
				this.Onq26Changing(value);
				this.SendPropertyChanging();
				this._q26 = value;
				this.SendPropertyChanged("q26");
				this.Onq26Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q27", DbType="Int")]
	public System.Nullable<int> q27
	{
		get
		{
			return this._q27;
		}
		set
		{
			if ((this._q27 != value))
			{
				this.Onq27Changing(value);
				this.SendPropertyChanging();
				this._q27 = value;
				this.SendPropertyChanged("q27");
				this.Onq27Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q28", DbType="Int")]
	public System.Nullable<int> q28
	{
		get
		{
			return this._q28;
		}
		set
		{
			if ((this._q28 != value))
			{
				this.Onq28Changing(value);
				this.SendPropertyChanging();
				this._q28 = value;
				this.SendPropertyChanged("q28");
				this.Onq28Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q29", DbType="Int")]
	public System.Nullable<int> q29
	{
		get
		{
			return this._q29;
		}
		set
		{
			if ((this._q29 != value))
			{
				this.Onq29Changing(value);
				this.SendPropertyChanging();
				this._q29 = value;
				this.SendPropertyChanged("q29");
				this.Onq29Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q30", DbType="Int")]
	public System.Nullable<int> q30
	{
		get
		{
			return this._q30;
		}
		set
		{
			if ((this._q30 != value))
			{
				this.Onq30Changing(value);
				this.SendPropertyChanging();
				this._q30 = value;
				this.SendPropertyChanged("q30");
				this.Onq30Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q31", DbType="Int")]
	public System.Nullable<int> q31
	{
		get
		{
			return this._q31;
		}
		set
		{
			if ((this._q31 != value))
			{
				this.Onq31Changing(value);
				this.SendPropertyChanging();
				this._q31 = value;
				this.SendPropertyChanged("q31");
				this.Onq31Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q32", DbType="Int")]
	public System.Nullable<int> q32
	{
		get
		{
			return this._q32;
		}
		set
		{
			if ((this._q32 != value))
			{
				this.Onq32Changing(value);
				this.SendPropertyChanging();
				this._q32 = value;
				this.SendPropertyChanged("q32");
				this.Onq32Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q33", DbType="Int")]
	public System.Nullable<int> q33
	{
		get
		{
			return this._q33;
		}
		set
		{
			if ((this._q33 != value))
			{
				this.Onq33Changing(value);
				this.SendPropertyChanging();
				this._q33 = value;
				this.SendPropertyChanged("q33");
				this.Onq33Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q34", DbType="Int")]
	public System.Nullable<int> q34
	{
		get
		{
			return this._q34;
		}
		set
		{
			if ((this._q34 != value))
			{
				this.Onq34Changing(value);
				this.SendPropertyChanging();
				this._q34 = value;
				this.SendPropertyChanged("q34");
				this.Onq34Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_q35", DbType="Int")]
	public System.Nullable<int> q35
	{
		get
		{
			return this._q35;
		}
		set
		{
			if ((this._q35 != value))
			{
				this.Onq35Changing(value);
				this.SendPropertyChanging();
				this._q35 = value;
				this.SendPropertyChanged("q35");
				this.Onq35Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
